version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      bash -c "poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=dinodu93
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=housing
    env_file:
      - .env
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dinodu93
      POSTGRES_DB: housing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
